<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="APPEND" Id="{ce0d917d-1e4e-433e-812a-e1ca7a7edc98}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION APPEND : STRING
VAR_INPUT
	STRING_TO_APPEND,
	STRING1,
	STRING2:	STRING;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[STRING_TO_APPEND := CONCAT(STRING_TO_APPEND, STRING1);
APPEND := CONCAT(STRING_TO_APPEND, STRING2);]]></ST>
    </Implementation>
    <LineIds Name="APPEND">
      <LineId Id="11" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>