<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="POLY" Id="{289288d7-34a1-48c9-a091-6574769f9ed1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POLY : LREAL
VAR_INPUT
	X:	LREAL;
	COEFFS: ARRAY [0..3] OF LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[POLY := COEFFS[0]*EXPT(X, 0) + COEFFS[1]*EXPT(X, 1) + COEFFS[2]*EXPT(X, 2) + COEFFS[3]*EXPT(X, 3);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>